name: Build ClipboardSync
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore app
        run: dotnet restore ClipboardSyncApp/ClipboardSyncApp.csproj
      - name: Restore tests
        run: dotnet restore ClipboardSync.Tests/ClipboardSync.Tests.csproj
      - name: Build app
        run: dotnet build ClipboardSyncApp/ClipboardSyncApp.csproj --configuration Release --no-restore
      - name: Build tests
        run: dotnet build ClipboardSync.Tests/ClipboardSync.Tests.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ClipboardSync.Tests/ClipboardSync.Tests.csproj --configuration Release --no-build --logger "console;verbosity=minimal"
      - name: Publish
        run: dotnet publish ClipboardSyncApp/ClipboardSyncApp.csproj --configuration Release --output ./publish --no-build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClipboardSync
          path: ./publish
